# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-18 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ip',
            old_name='ip',
            new_name='ip_address',
        ),
    ]
