# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-19 05:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170318_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='room',
        ),
        migrations.RemoveField(
            model_name='home',
            name='houskeeper',
        ),
        migrations.RemoveField(
            model_name='room',
            name='house',
        ),
        migrations.DeleteModel(
            name='device',
        ),
        migrations.DeleteModel(
            name='home',
        ),
        migrations.DeleteModel(
            name='room',
        ),
    ]
