# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-22 13:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='houskeeper',
            new_name='house_keeper',
        ),
        migrations.RemoveField(
            model_name='device',
            name='functional',
        ),
        migrations.RemoveField(
            model_name='room',
            name='house',
        ),
        migrations.AddField(
            model_name='device',
            name='description',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='mode',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='device',
            name='value',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='home',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='homes.Home'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homes.Room'),
        ),
        migrations.AlterField(
            model_name='home',
            name='address',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
