# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-24 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0002_home_home_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_name',
            field=models.CharField(default='my device', max_length=128),
        ),
        migrations.AlterField(
            model_name='home',
            name='home_name',
            field=models.CharField(default='main house', max_length=128),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_name',
            field=models.CharField(default='my room', max_length=64),
        ),
    ]
